# Generated by Django 4.1.3 on 2022-11-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='catchRate',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='height',
        ),
    ]
